---
- name: Create a resource group
  azure_rm_resourcegroup:
    name: "{{ azr_resource_group }}"
    location: "{{ azr_location }}"
    state: present
    tags: "{{ azr_tags }}"

- name: Create a virtual network
  azure.azcollection.azure_rm_virtualnetwork:
    resource_group: "{{ azr_resource_group }}"
    name: "{{ azr_virtual_network.name }}"
    address_prefixes_cidr: "{{ azr_virtual_network.address_prefixes_cidr }}"
    tags: "{{ azr_tags }}"

- name: Get Azure Firewall
  azure_rm_azurefirewall_info:
    resource_group: "{{ azr_resource_group }}"
    name: firewall
  register: _firewall
  when:
    - azr_aro_egress_lockdown | bool
  failed_when: false

# - block:
#     - debug:
#         msg: "Waiting for cluster to finish provisioning."

#     - async_status:
#         jid: "{{ _aro_create.ansible_job_id }}"
#       register: _aro_create_status
#       until: _aro_create_status.finished
#       retries: 120
#       delay: 60
#   when: (_aro_create is defined) and ("ansible_job_id" in _aro_create.keys())

# - name: check cluster
#   shell: |
#     az aro show \
#     --resource-group {{ azr_resource_group }} \
#     --name {{ azr_aro_cluster }}
#   register: _aro_check
#   failed_when: False
#   changed_when: False

# - fail:
#     msg: "Cluster {{ azr_aro_cluster }} failed to provision."
#   when: (_aro_check.rc == 0) and ((_aro_check.stdout | from_json).provisioningState == "Failed")

- block:
    - name: Create a control subnet
      azure_rm_subnet:
        resource_group: "{{ azr_resource_group }}"
        virtual_network_name: "{{ azr_virtual_network.name }}"
        name: "{{ azr_aro_control_subnet.name }}"
        address_prefix_cidr: "{{ azr_aro_control_subnet.address_prefix_cidr }}"
        service_endpoints:
          - service: "Microsoft.ContainerRegistry"
        private_link_service_network_policies: Disabled
      register: _control_subnet

    - name: Create a machine subnet
      azure_rm_subnet:
        resource_group: "{{ azr_resource_group }}"
        virtual_network_name: "{{ azr_virtual_network.name }}"
        name: "{{ azr_aro_machine_subnet.name }}"
        address_prefix_cidr: "{{ azr_aro_machine_subnet.address_prefix_cidr }}"
        service_endpoints:
          - service: "Microsoft.ContainerRegistry"
      register: _machine_subnet
  when: (_firewall.firewalls is not defined) or
        (not _cluster_ready | default(False))

- block:
    - name: Update a control subnet to use egress route
      azure_rm_subnet:
        resource_group: "{{ azr_resource_group }}"
        virtual_network_name: "{{ azr_virtual_network.name }}"
        name: "{{ azr_aro_control_subnet.name }}"
        address_prefix_cidr: "{{ azr_aro_control_subnet.address_prefix_cidr }}"
        service_endpoints:
          - service: "Microsoft.ContainerRegistry"
        private_link_service_network_policies: Disabled
        route_table:
          name: aroRouteTable
          resource_group: "{{ azr_resource_group }}"

    - name: update machine subnet to use egress route
      azure_rm_subnet:
        resource_group: "{{ azr_resource_group }}"
        virtual_network_name: "{{ azr_virtual_network.name }}"
        name: "{{ azr_aro_machine_subnet.name }}"
        address_prefix_cidr: "{{ azr_aro_machine_subnet.address_prefix_cidr }}"
        service_endpoints:
          - service: "Microsoft.ContainerRegistry"
        route_table:
          name: aroRouteTable
          resource_group: "{{ azr_resource_group }}"
  when:
    - _firewall.firewalls is defined
    - azr_aro_egress_lockdown | bool
    - _cluster_ready | default(False)
# - debug:
#     var: _control_subnet

# - debug:
#     var: _machine_subnet


    # var "{{ _control_subnet.id }}"
    # msg: "{{ _machine_subnet.id }}"

