---
- name: Delete cluster
  azure.azcollection.azure_rm_openshiftmanagedcluster:
    resource_group: "{{ azr_resource_group }}"
    name: "{{ azr_aro_cluster }}"
    location: "{{ azr_location }}"
    state: absent
